package com.jswl.portal.entity;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.title
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.column_id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private Integer columnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.releas_time
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private Long releasTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.status
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.sort
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.recommend
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private Integer recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.create_time
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.create_user_id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.modify_time
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private Long modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.modify_user_id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private Integer modifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.content
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.id
     *
     * @return the value of t_article.id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.id
     *
     * @param id the value for t_article.id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.title
     *
     * @return the value of t_article.title
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.title
     *
     * @param title the value for t_article.title
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.column_id
     *
     * @return the value of t_article.column_id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.column_id
     *
     * @param columnId the value for t_article.column_id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.releas_time
     *
     * @return the value of t_article.releas_time
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public Long getReleasTime() {
        return releasTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.releas_time
     *
     * @param releasTime the value for t_article.releas_time
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setReleasTime(Long releasTime) {
        this.releasTime = releasTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.status
     *
     * @return the value of t_article.status
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.status
     *
     * @param status the value for t_article.status
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.sort
     *
     * @return the value of t_article.sort
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.sort
     *
     * @param sort the value for t_article.sort
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.recommend
     *
     * @return the value of t_article.recommend
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.recommend
     *
     * @param recommend the value for t_article.recommend
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.create_time
     *
     * @return the value of t_article.create_time
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.create_time
     *
     * @param createTime the value for t_article.create_time
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.create_user_id
     *
     * @return the value of t_article.create_user_id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.create_user_id
     *
     * @param createUserId the value for t_article.create_user_id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.modify_time
     *
     * @return the value of t_article.modify_time
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.modify_time
     *
     * @param modifyTime the value for t_article.modify_time
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.modify_user_id
     *
     * @return the value of t_article.modify_user_id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.modify_user_id
     *
     * @param modifyUserId the value for t_article.modify_user_id
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.content
     *
     * @return the value of t_article.content
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.content
     *
     * @param content the value for t_article.content
     *
     * @mbggenerated Thu Sep 19 15:31:21 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}